# Generated by Django 5.1.5 on 2025-02-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WaterIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(help_text="Amount of water in ounces")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
