# Generated by Django 5.1.5 on 2025-02-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tracker",
            "0002_remove_waterintake_timestamp_waterintake_entry_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterintake",
            name="liquid_type",
            field=models.CharField(
                choices=[
                    ("water", "Water"),
                    ("sparkling water", "Sparkling Water"),
                    ("coffee", "Coffee"),
                    ("tea", "Tea"),
                    ("juice", "Juice"),
                    ("soda", "Soda"),
                    ("beer", "Beer"),
                    ("wine", "Wine"),
                    ("other", "Other"),
                ],
                default="water",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="waterintake",
            name="person",
            field=models.CharField(
                choices=[("sebo", "Sebo"), ("alomi", "Alomi")],
                default="alomi",
                max_length=10,
            ),
        ),
    ]
