# Generated by Django 5.1.5 on 2025-02-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_waterintake_liquid_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterintake",
            name="liquid_type",
            field=models.CharField(
                choices=[
                    ("water", "Water"),
                    ("sparkling water", "Sparkling Water"),
                    ("coffee", "Coffee"),
                    ("tea", "Tea"),
                    ("milk", "Milk"),
                    ("juice", "Juice"),
                    ("soda", "Soda"),
                    ("beer", "Beer"),
                    ("wine", "Wine"),
                    ("other", "Other"),
                ],
                default="water",
                max_length=50,
            ),
        ),
    ]
